#!/usr/bin/env bash

aur=true
wrapper="yay"
sudoBin="sudo"
termFont="true"

mngHideFlatpak=false
mngHideHeaders=false
mngHideNums=false
mngHideHelp=false

flatpakRemoveUnused=true
flatpakFlags="--system -y"

fzfOptions=""
